version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://ep-orange-bush-a5y0gfft.us-east-2.aws.neon.tech/AmazonBooksApi?&sslmode=require
      - SPRING_DATASOURCE_USERNAME=$neondb_owner
      - SPRING_DATASOURCE_PASSWORD=$9r8nPgyDWXwB

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=$compose-postgres
        - POSTGRES_PASSWORD=$compose-postgres
